everything is working 100% when it comes to creating users - it's damn ugly, but it works

diff --git a/redeploy b/redeploy
--- a/redeploy
+++ b/redeploy
@@ -5,6 +5,16 @@ docker compose stop ssui
 
 echo "... building new container ..."
 mvn clean package
+
+if [ $? -eq 0 ]; then
+  echo "mvn compile successful, building docker image and redeploying ..."
+else
+  echo "mvn compile failed, exiting..."
+  exit 1
+fi
+
+
+
 cd docker
 docker build -t soberstreak:1 .
 cd ..
@@ -15,4 +25,12 @@ docker rm ssui
 echo "... redeploysing newest build ..."
 docker compose up -d ssui
 
-#docker compose logs -f ssui
+# Check if the -l argument is present
+while getopts "l" opt; do
+  case $opt in
+    l)
+      echo "Fetching logs..."
+      docker compose logs -f ssui
+      ;;
+  esac
+done
